name: Deploy fronted to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "code/frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add frontend remote origin
        run: heroku git:remote -a chicken-tinder-13
      - name: Deploy frontend to Heroku
        run: git push heroku main
        
  
