name: Deploy backend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "code/backend/sparkjava/**"
      - ".github/workflows/sparkjava.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Deploy backend to Heroku
        run: git push heroku-backend `git subtree split --prefix code/backend/sparkjava main`:refs/heads/main --force
